package com.myspace.insident_management.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Alarm implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "ALARM_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "ALARM_ID_GENERATOR", sequenceName = "ALARM_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Alarm name")
	private java.lang.String alarmName;

	@org.kie.api.definition.type.Label(value = "Alarm serverity")
	private java.lang.String alarmServerity;

	@org.kie.api.definition.type.Label(value = "Alarm number")
	private java.lang.String alarmNumber;

	@org.kie.api.definition.type.Label(value = "Alarm node")
	private java.lang.String alarmNode;

	@org.kie.api.definition.type.Label(value = "Start time")
	private java.time.LocalDateTime startTime;

	@org.kie.api.definition.type.Label(value = "End time")
	private java.time.LocalDateTime endTime;

	public Alarm() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getAlarmName() {
		return this.alarmName;
	}

	public void setAlarmName(java.lang.String alarmName) {
		this.alarmName = alarmName;
	}

	public java.lang.String getAlarmServerity() {
		return this.alarmServerity;
	}

	public void setAlarmServerity(java.lang.String alarmServerity) {
		this.alarmServerity = alarmServerity;
	}

	public java.lang.String getAlarmNumber() {
		return this.alarmNumber;
	}

	public void setAlarmNumber(java.lang.String alarmNumber) {
		this.alarmNumber = alarmNumber;
	}

	public java.lang.String getAlarmNode() {
		return this.alarmNode;
	}

	public void setAlarmNode(java.lang.String alarmNode) {
		this.alarmNode = alarmNode;
	}

	public java.time.LocalDateTime getStartTime() {
		return this.startTime;
	}

	public void setStartTime(java.time.LocalDateTime startTime) {
		this.startTime = startTime;
	}

	public java.time.LocalDateTime getEndTime() {
		return this.endTime;
	}

	public void setEndTime(java.time.LocalDateTime endTime) {
		this.endTime = endTime;
	}

	public Alarm(java.lang.Long id, java.lang.String alarmName,
			java.lang.String alarmServerity, java.lang.String alarmNumber,
			java.lang.String alarmNode, java.time.LocalDateTime startTime,
			java.time.LocalDateTime endTime) {
		this.id = id;
		this.alarmName = alarmName;
		this.alarmServerity = alarmServerity;
		this.alarmNumber = alarmNumber;
		this.alarmNode = alarmNode;
		this.startTime = startTime;
		this.endTime = endTime;
	}

}