package com.myspace.insident_management.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class IncidentOwner implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "INCIDENTOWNER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "INCIDENTOWNER_ID_GENERATOR", sequenceName = "INCIDENTOWNER_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "Mobile number")
	private java.lang.String mobileNumber;

	@org.kie.api.definition.type.Label(value = "Company")
	private java.lang.String company;

	@org.kie.api.definition.type.Label(value = "Join date")
	private java.lang.String joinDate;

	@org.kie.api.definition.type.Label(value = "ETC")
	private java.lang.String etc;

	public IncidentOwner() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(java.lang.String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public java.lang.String getCompany() {
		return this.company;
	}

	public void setCompany(java.lang.String company) {
		this.company = company;
	}

	public java.lang.String getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(java.lang.String joinDate) {
		this.joinDate = joinDate;
	}

	public java.lang.String getEtc() {
		return this.etc;
	}

	public void setEtc(java.lang.String etc) {
		this.etc = etc;
	}

	public IncidentOwner(java.lang.Long id, java.lang.String name,
			java.lang.String mobileNumber, java.lang.String company,
			java.lang.String joinDate, java.lang.String etc) {
		this.id = id;
		this.name = name;
		this.mobileNumber = mobileNumber;
		this.company = company;
		this.joinDate = joinDate;
		this.etc = etc;
	}

}