package com.myspace.insident_management.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Incident implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "INCIDENT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "INCIDENT_ID_GENERATOR", sequenceName = "INCIDENT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Incident cause")
	private java.lang.String incidentCause;

	@org.kie.api.definition.type.Label("Incident number")
	private java.lang.String incidentNumber;

	@org.kie.api.definition.type.Label("Incident owner")
	private java.lang.String incidentOwner;

	@org.kie.api.definition.type.Label("Incident impact")
	private java.lang.String incidentImpact;

	@org.kie.api.definition.type.Label("Service impacted")
	private java.lang.String serviceImpacted;

	@org.kie.api.definition.type.Label("Recovery time")
	private java.lang.String recoveryTime;

	@org.kie.api.definition.type.Label("Incident RCA")
	private java.lang.String incidentRCA;

	@org.kie.api.definition.type.Label("Incident status")
	private java.lang.String incidentStatus;

	@org.kie.api.definition.type.Label("Incident CR Related")
	private java.lang.String incidentCRrelated;

	@org.kie.api.definition.type.Label(value = "Comment")
	private java.lang.String comment;

	public Incident() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getIncidentCause() {
		return this.incidentCause;
	}

	public void setIncidentCause(java.lang.String incidentCause) {
		this.incidentCause = incidentCause;
	}

	public java.lang.String getIncidentNumber() {
		return this.incidentNumber;
	}

	public void setIncidentNumber(java.lang.String incidentNumber) {
		this.incidentNumber = incidentNumber;
	}

	public java.lang.String getIncidentOwner() {
		return this.incidentOwner;
	}

	public void setIncidentOwner(java.lang.String incidentOwner) {
		this.incidentOwner = incidentOwner;
	}

	public java.lang.String getIncidentImpact() {
		return this.incidentImpact;
	}

	public void setIncidentImpact(java.lang.String incidentImpact) {
		this.incidentImpact = incidentImpact;
	}

	public java.lang.String getServiceImpacted() {
		return this.serviceImpacted;
	}

	public void setServiceImpacted(java.lang.String serviceImpacted) {
		this.serviceImpacted = serviceImpacted;
	}

	public java.lang.String getRecoveryTime() {
		return this.recoveryTime;
	}

	public void setRecoveryTime(java.lang.String recoveryTime) {
		this.recoveryTime = recoveryTime;
	}

	public java.lang.String getIncidentRCA() {
		return this.incidentRCA;
	}

	public void setIncidentRCA(java.lang.String incidentRCA) {
		this.incidentRCA = incidentRCA;
	}

	public java.lang.String getIncidentStatus() {
		return this.incidentStatus;
	}

	public void setIncidentStatus(java.lang.String incidentStatus) {
		this.incidentStatus = incidentStatus;
	}

	public java.lang.String getIncidentCRrelated() {
		return this.incidentCRrelated;
	}

	public void setIncidentCRrelated(java.lang.String incidentCRrelated) {
		this.incidentCRrelated = incidentCRrelated;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public Incident(java.lang.Long id, java.lang.String incidentCause,
			java.lang.String incidentNumber, java.lang.String incidentOwner,
			java.lang.String incidentImpact, java.lang.String serviceImpacted,
			java.lang.String recoveryTime, java.lang.String incidentRCA,
			java.lang.String incidentStatus,
			java.lang.String incidentCRrelated, java.lang.String comment) {
		this.id = id;
		this.incidentCause = incidentCause;
		this.incidentNumber = incidentNumber;
		this.incidentOwner = incidentOwner;
		this.incidentImpact = incidentImpact;
		this.serviceImpacted = serviceImpacted;
		this.recoveryTime = recoveryTime;
		this.incidentRCA = incidentRCA;
		this.incidentStatus = incidentStatus;
		this.incidentCRrelated = incidentCRrelated;
		this.comment = comment;
	}

}