package com.myspace.insident_management.models;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RootCauseCategories implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "ROOTCAUSECATEGORIES_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "ROOTCAUSECATEGORIES_ID_GENERATOR", sequenceName = "ROOTCAUSECATEGORIES_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "RCA")
	private java.lang.String rca;

	public RootCauseCategories() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getRca() {
		return this.rca;
	}

	public void setRca(java.lang.String rca) {
		this.rca = rca;
	}

	public RootCauseCategories(java.lang.Long id, java.lang.String rca) {
		this.id = id;
		this.rca = rca;
	}

}